name: Unit Test

on:
  pull_request:
    branches:
      - "**" # すべてのPRに対して実行

jobs:
  unit_test:
    runs-on: macos-latest-xlarge
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Execute Unit Test
        run: bundle exec fastlane scan
        env:
          TZ: Asia/Tokyo