name: Unit Test

on:
  pull_request:
    branches:
      - "**" # すべてのPRに対して実行

jobs:
  unit_test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
            xcode-version: latest-stable

      - name: Setup
        uses: ./.github/actions/setup

      - name: Execute Unit Test
        run: bundle exec fastlane scan
        env:
          TZ: Asia/Tokyo